site_name: MDify

theme: 
  name: mkdocs
  color_mode: auto
  nav_style: dark
  user_color_mode_toggle: true
  navigation_depth: 5

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 3
            show_category_heading: false
            show_symbol_type_heading: true
            docstring_section_style: list
            show_symbol_type_toc: false

nav:
  - Home: index.md
  - Reference: reference.md
  - Usage: usage.md